# Generated by Django 3.2.8 on 2021-11-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sell_rent',
            field=models.CharField(choices=[('S', 'To Sell'), ('R', 'To Rent')], default='S', max_length=1),
        ),
    ]
