# Generated by Django 3.2.8 on 2021-11-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211128_1436'),
        ('blog', '0004_auto_20211128_1612'),
    ]

    operations = [
    ]
