# Generated by Django 3.2.8 on 2021-11-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_merge_0004_auto_20211128_1436_0004_auto_20211128_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='place',
        ),
    ]
