# Generated by Django 3.2.8 on 2021-12-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('H', 'House'), ('A', 'Apartment'), ('G', 'Garage')], default='H', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='localisation',
            field=models.CharField(default='Bruxelles', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='surface',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
