# Generated by Django 3.2.8 on 2021-12-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211208_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.TextField(default='Boulevard du Triomphe 1 accès 2, Batiment HA, CP 220/01, 1050 Bruxelles'),
        ),
    ]
