# Generated by Django 3.2.8 on 2021-12-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.TextField(default='Boulevard du Triomphe 1 , 1050 Bruxelles'),
        ),
    ]
