# Generated by Django 3.2.8 on 2021-12-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lat',
            field=models.FloatField(blank=True, default='50', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='long',
            field=models.FloatField(blank=True, default='50', null=True),
        ),
    ]
