# Generated by Django 3.2.8 on 2021-12-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20211208_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
