# Generated by Django 3.2.8 on 2021-12-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20211208_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_views',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
        ),
    ]
