# Generated by Django 3.2.8 on 2021-12-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_number_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number_views',
            field=models.IntegerField(default=0),
        ),
    ]
