# Generated by Django 3.2.8 on 2021-12-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_number_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(default='defaultAnnounce.jpg', upload_to='announce_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(default='defaultAnnounce.jpg', upload_to='announce_pics'),
        ),
    ]
