# Generated by Django 3.2.8 on 2021-12-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20211215_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(default='defaultAnnounce.jpg', upload_to='announce_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(default='defaultAnnounce.jpg', upload_to='announce_pics'),
        ),
    ]
