# Generated by Django 3.2.8 on 2021-12-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20211215_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='room_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
