# Generated by Django 4.0 on 2021-12-26 12:19

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_messages_delete_chatmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=[300, 300], default='defaultAnnounce.jpg', force_format=None, keep_meta=True, quality=0, size=[1920, 1080], upload_to='announce_pics'),
        ),
    ]
