# Generated by Django 4.0 on 2021-12-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='defaultAnnounce.jpg', upload_to='announce_pics'),
        ),
    ]
