# Generated by Django 3.2.8 on 2021-12-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='localisation_preference',
            field=models.CharField(default='Bruxelles', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='price_preference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='sell_rent_preference',
            field=models.CharField(choices=[('S', 'To Sell'), ('R', 'To Rent')], default='S', max_length=10),
        ),
    ]
